### ISSUE TITLE
[feature request] hide the notification

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-flutter#101]
![](https://cdn.discordapp.com/attachments/1245346269501587496/1245346269736599643/IMG_1387.png?ex=66586a98&is=66571918&hm=159ca77a1b8d62def7928a145bfe285dc66b7ab58771815b1d2996b58386652f&)

> Is it possible to disable the arrow appearing in the dynamic island? (iOS 17.5.1 see screenshot)
> I could not disable Live Activities in the Noa app’s preferences (in the Settings app)

https://discord.com/channels/963222352534048818/1245346269501587496

**Comment by siliconwitch** [comment]
Don't think it's possible since the app is always keeping the latest location so that Frame can pass it along with the question when making requests. Additionally, the location can't be stopped or started **from** background mode. i.e. we can't get location only on bluetooth events. It has to always be on. Otherwise, this would allow apps to sneakily track your location using any background event, and you'd never know because the icon comes and goes too quickly. Here the phone is telling the user that the location is active. Eventually though, if the user isn't moving, it will go away.

Apple allow this to be hidden by the user if they like. Go into the system app settings and selects "Always" for location. Then the icon will go away

**Comment by josuah** [comment]
One workaround seems to be:

> changing permission to “Ask next time …” and the arrow is no longer there.

Thank you for the swift reply!
