### ISSUE TITLE
Add Github OAuth login

### ISSUE THREAD

**Issue by WuerfelDev** [brilliantlabsAR/noa-flutter#73]
As open source app with many developers as users it would be great to log in via Github: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps

**Comment by siliconwitch** [comment]
We considered this, but it became too many login options on the start screen. Already include Apple, Google, and email login. Since we don't use the Oauth for anything other than access, there's nothing special gained with a particular provider. Maybe we'll add it someday if there's a need for it. For example, sharing or accessing scripts from GitHub, for now, we've kept it simple by just having these three options

**Comment by WuerfelDev** [comment]
Great :)
I wasn't aware of email (as it wasn't available in the old android app). My toughts were that adding another oauth login would be easier for you on the backend than managing accounts yourself
